### ISSUE TITLE
Typescript Interfaces error: Expected indentation of 4 spaces but found 2.

### ISSUE THREAD

**Issue by jonzee** [progre/tslint-config-airbnb#1]
Hi! Thanks a lot for linter with `airbnb` style guide, I have a problem with `interfaces`, linter expects bigger indentation (when I have 2 spaces, it needs 4 spaces, when I fixed to 4, it's expects 6 etc.). To reproduce create multiline interface:
```
export interface User {
  email: string;
  photo: string;
}
...
Expected indentation of 4 spaces but found 2.
Expected indentation of 4 spaces but found 2.
```
P.S. the same story is with decorators `@Deco('rator')`

**Comment by progre** [comment]
I tried same code that your interface, but it has no error. It's needed 2 spaces.
Are you use it with other rules? Please check your tslint.json.
Thanks.

**Comment by jonzee** [comment]
My tslint.json
```
{
  "extends": "tslint-config-airbnb"
}
```

**Comment by progre** [comment]
Cool. You use tslint@4.5.1 (latest), and if fail, try custom rule;
```
{
  "extends": "tslint-config-airbnb",
  "rules": {
    "ter-indent": [false]
  }
}
```

**Comment by jonzee** [comment]
Yep, now it's working, thanks a lot!
