### ISSUE TITLE
Could not find implementations for the following rules specified in the configuration

### ISSUE THREAD

**Issue by destroyerofbuilds** [progre/tslint-config-airbnb#11]
We're encountering the following warnings while using `tslint-config-airbnb` with the latest version of `tslint`:

```bash
$ ./node_modules/.bin/tslint --fix src/tasks/tslint.ts --project tsconfig.json

Could not find implementations for the following rules specified in the configuration:
    no-unused-expressions
    no-shadow-variable
```

```bash
$ ./node_modules/.bin/tslint --version
5.4.3
```

**Comment by progre** [comment]
>    no-unused-expressions
>    no-shadow-variable
Both rules is not use from tslint-config-airbnb.
Please check your rule file.

**Comment by destroyerofbuilds** [comment]
@progre it seems I had made typos in my `tslint` rule file (which extends `tsling-config-airbnb` with a few additional options).

After correcting those typos I am, quite obviously, not encountering the message documented in my first post.

Thank you for your help.
