### ISSUE TITLE
warning "tslint-microsoft-contrib@5.0.0" has incorrect peer dependency "tsutils@1.6.0".

### ISSUE THREAD

**Issue by destroyerofbuilds** [progre/tslint-config-airbnb#12]
We're seeing `warning "tslint-microsoft-contrib@5.0.0" has incorrect peer dependency "tsutils@1.6.0".` in the output while installing `tslint-config-airbnb` with `yarn`.

In `npm` we get `npm WARN tslint-microsoft-contrib@5.0.0 requires a peer of tsutils@1.6.0 but none was installed.`

**Comment by progre** [comment]
I think peer dependency needs to be installed on your project dependencies.

**Comment by destroyerofbuilds** [comment]
Looks like this came up in Microsoft/tslint-microsoft-contrib#373.

A fix has been submitted but not yet released - https://github.com/Microsoft/tslint-microsoft-contrib/commit/d33dbf6d04632c1494c2772960448d93e53087c6

**Comment by progre** [comment]
It will be fixed when tslint-microsoft-contrib is released.
