### ISSUE TITLE
5.2.0 gone from npm?

### ISSUE THREAD

**Issue by icorne** [progre/tslint-config-airbnb#15]
Hello,

Has version 5.2.0 been unpublished?

**Comment by dashmug** [comment]
Looks like it.
My scripts relying on `npm outdated` are now failing.

**Comment by jefftougas** [comment]
We're seeing the same problem.

**Comment by dashmug** [comment]
Have to use `v5.1.2` until the author fixes this.

**Comment by progre** [comment]
```v5.2.1``` was released now.

**Comment by dashmug** [comment]
Thanks @progre!
