### ISSUE TITLE
Semanic Version Policy

### ISSUE THREAD

**Issue by destroyerofbuilds** [progre/tslint-config-airbnb#18]
I was curious whether you take a semantic versioning approach to releasing changes to `tslist-config-airbnb`?

For example b4210920617bcf1366e5cf11ba473a15bfb47fac made an existing rule stricter, which would be a breaking change in that using version 5.2.0 on the same code base as 5.1 would cause `tslint` to fail.

Should we interact with `tslint-config-airbnb` as if any release could contain stricter rules and cause `tslint` to fail on previously passing code?

**Comment by progre** [comment]
This module is strongly dependent to tslint.
I think it should match the major version with tslint for make it easy to understand.

**Comment by destroyerofbuilds** [comment]
Thank you @progre. Could a short summary be added to the `README.md` explaining how major versions will track `tslint`, and minor versions may introduce new enforcement rules? (I'd like something I can link to from a commit message that changes the version pattern from `^` to `~` to ensure only patch versions are picked up automatically.)

**Comment by progre** [comment]
i added readme.
