### ISSUE TITLE
Update function name for AngularJS methods

### ISSUE THREAD

**Issue by mlavina** [progre/tslint-config-airbnb#24]
I am trying to use this tslint config with a frontend project using AngularJS and Typescript. However, I get tslinting errors for Angular methods such as `$onInit()` and `$postLink()` because of the regex matching here https://github.com/progre/tslint-config-airbnb/blob/a0f5a6b21f23e3488dfe2fef904aa1f135bc02f0/tslint.js#L121

And looking at the `AirBnB` standards https://github.com/airbnb/javascript#naming-conventions there doesn't seem to be anything that would make a leading `$` a problem.

**Comment by destroyerofbuilds** [comment]
It looks like the only rules are no leading or trailing underscores, no single letter names, and use proper casing.

So changing the regex to relax the current requirements would really help avoid integration issues with frameworks that use various naming conventions that still, technically, comply with the AirBnB standard.

**Comment by progre** [comment]
Thx for your report.
This issue was fixed by 5.4.2
