### ISSUE TITLE
Warnings when using base configuration

### ISSUE THREAD

**Issue by ericmasiello** [progre/tslint-config-airbnb#25]
When running tslint using tslint-config-aribnb using the following command:
`tslint 'src/**/*.ts?(x)' tsconfig.json`

and the following tsconfig.json:

```
{
  "extends": ["tslint-config-airbnb"]
}
```

I see the following warnings output:

```
Warning: The 'no-boolean-literal-compare' rule requires type information.
Warning: The 'strict-boolean-expressions' rule requires type information.
```

**Comment by Sly777** [comment]
@ericmasiello if you use ``` -p tsconfig.json``` when you run lint, It will disappear.

info: https://palantir.github.io/tslint/usage/type-checking/
