### ISSUE TITLE
Unmet peer dependencies

### ISSUE THREAD

**Issue by noxan** [progre/tslint-config-airbnb#3]
```
warning "tslint-eslint-rules@3.4.0" has unmet peer dependency "tslint@^4.0.0".
warning "tslint@4.5.1" has unmet peer dependency "typescript@>=2.0.0".
warning "tsutils@1.1.0" has unmet peer dependency "typescript@>=2.0.0".
warning "tslint-microsoft-contrib@4.0.1" has unmet peer dependency "tslint@>=4.0.0".
```

I would be willing to provide a pull request.

**Comment by progre** [comment]
I think tslint and typescript should be installed by user. A warning when npm install only this package is no problem.

**Comment by ibujs** [comment]
Or perhaps your app has outdated TSLint and TypeScript versions. These are not issues with this package, but are requirements of its dependencies.

**Comment by noxan** [comment]
Sorry if I got it wrong. I never intended to have those as dependencies instead.

I was just wondering if it wouldn't be nice to have them as included also dev dependencies so you can work on this package without running the lines @ibujs wrote above. In the end calling these with `--save-dev` would have exactly the result I was looking for.

For example the official airbnb eslint package does exactly this, see https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb-base/package.json.

**Comment by ibujs** [comment]
Wait, what is the exact issue? If you're talking about this issue on an app, then you should include typescript and tslint as devDependencies unless there may be some special circumstances for typescript.
