### ISSUE TITLE
Rule 16.1

### ISSUE THREAD

**Issue by jeremejevs** [progre/tslint-config-airbnb#31]
I think [`curly`](https://palantir.github.io/tslint/rules/curly/) covers the non-function part of [16.1](https://github.com/airbnb/javascript#blocks--braces) pretty well:

```js
curly: [true, 'ignore-same-line']
```

**Comment by progre** [comment]
This was included in 5.7.0.
Thanks for your suggestion!

**Comment by jeremejevs** [comment]
Thanks for acting on this so promptly!
