### ISSUE TITLE
PascalCase

### ISSUE THREAD

**Issue by jeremejevs** [progre/tslint-config-airbnb#32]
The following code currently gets flagged by `variable-name`:

```js
const App = () => <div>Hello world!</div>;
```

The style guide discourages the use of name inference ([here](https://github.com/airbnb/javascript#functions--declarations) and [here](https://github.com/airbnb/javascript/tree/master/react#class-vs-reactcreateclass-vs-stateless)), so that kind of makes the example above (the notation I personally prefer) invalid, but not this one:

```js
const App = function App() { return <div>Hello world!</div> };
```

I think the rule should be changed to this:

```js
'variable-name': [true, 'check-format', 'allow-pascal-case']
```

A pure-component-specific exception would be nicer, of course, but, AFAIK, it doesn't exist.

**Comment by oliverbenns** [comment]
Related: https://github.com/progre/tslint-config-airbnb/issues/32

**Comment by progre** [comment]
I'm still confused whether Airbnb React/JSX Style should be included or not...

**Comment by jeremejevs** [comment]
Right, it never registered in my mind that this config is JS-only. At least currently. I'll close this then, since this is, indeed, a React-/JSX-specific problem.
