### ISSUE TITLE
The 'no-boolean-literal-compare' rule requires type information

### ISSUE THREAD

**Issue by krbaio3** [progre/tslint-config-airbnb#33]
I use tslint-config-airbnb, and to pass linter, the console throw me following warning:

```sh
$  node node_modules/.bin/tslint src/**/*.ts 
Warning: The 'no-boolean-literal-compare' rule requires type information.

ERROR: src/app/app-routing.module.ts[7, 50]: Missing trailing comma
ERROR: src/app/app-routing.module.ts[10, 50]: Missing trailing comma
ERROR: src/app/app-routing.module.ts[22, 20]: Missing trailing comma
[...]
ERROR: src/app/new.component.spec.ts[11, 36]: Missing trailing comma
ERROR: src/app/new.component.spec.ts[13, 7]: Missing trailing comma
ERROR: src/app/new.component.spec.ts[22, 7]: Missing trailing comma
ERROR: src/app/new.component.ts[5, 38]: Missing trailing comma
```

and, when I run the `--fix`, happens same

```sh
$  node node_modules/.bin/tslint src/**/*.ts --fix
Warning: The 'no-boolean-literal-compare' rule requires type information.

Fixed 1 error(s) in src/app/app.component.ts
[...]
Fixed 8 error(s) in src/app/app-routing.module.ts
```

After fix:

```sh
$ node node_modules/.bin/tslint src/**/*.ts
Warning: The 'no-boolean-literal-compare' rule requires type information.
```

What could be the problem?

Thanks!

versions:

**node**: v9.8.0
**npm**: 5.7.1
**tslint**: 5.9.1

**Comment by progre** [comment]
If it still throw without the ruleset, for example using something like this `tslint.json`

```
{
  "rules": {
    "no-boolean-literal-compare": true
  }
}
```

then I have no idea and I recommend to ask in tslint issue.

**Comment by sangaman** [comment]
I'm getting this exact same message, even with `"no-boolean-literal-compare": true`. Don't have time to open an issue with tslint at this moment but I'll probably open one this weekend.

**Comment by Deviad** [comment]
Same here.

**Comment by progre** [comment]
New issue created, so I close this.

**Comment by sangaman** [comment]
I figured out what the problem was, the solution is to pass `--project tsconfig.json` to the `tslint` command. Warning no longer displays after taking this step.
