### ISSUE TITLE
Updated to newest version of tslint-eslint-rules

### ISSUE THREAD

**Issue by mt-micky** [progre/tslint-config-airbnb#35]
`tslint-eslint-rules` is currently at version 5.1.0
It adds some good features from eslint that airbnb is using.

**Comment by progre** [comment]
Probably, I will add it along with rules that looks good.
Do you know the rules that look good?

**Comment by progre** [comment]
#36 is required a newer version of `tslint-eslint-rules`.

**Comment by progre** [comment]
merged
