### ISSUE TITLE
react-a11y-* from tslint-microsoft-contrib

### ISSUE THREAD

**Issue by joaovieira** [progre/tslint-config-airbnb#37]
Include `react-a11y-*` rules that match https://github.com/evcohen/eslint-plugin-jsx-a11y ?

**Comment by progre** [comment]
Currently I don't have a plan to add ~JSX~React subset(https://github.com/airbnb/javascript/tree/master/react).

**Comment by joaovieira** [comment]
Then this should be called `tslint-config-airbnb-base` (https://www.npmjs.com/package/eslint-config-airbnb-base). It's ridiculous to reject contributions that are right. Whatever...
