### ISSUE TITLE
"createLanguageServiceHost" is not a function and variable name must be in camelcase or uppercase

### ISSUE THREAD

**Issue by kctang** [progre/tslint-config-airbnb#4]
I am getting `Lint.createLanguageServiceHost` warning when running with this config.

As for the variable name, `Hello` is a component name so we should allow uppercase.

Thanks!

```
Warning: Lint.createLanguageServiceHost is not a function
ERROR: src/components/Hello.tsx[6, 14]: variable name must be in camelcase or uppercase
```

Source:
```
export const Hello = (props: HelloProps) => (
    <h1>Hello from {props.compiler}
        and {props.framework}!</h1>
);
```

**Comment by progre** [comment]
I don't found this error with your code in my workspace. I'm running vscode and tslint command.
You should try it with clean room. (and I will advise after look your workspace's dependencies.)

**Comment by sapegin** [comment]
I have the same issue:

```
Warning: Lint.createLanguageServiceHost is not a function
Warning: this.createFix is not a function
```

**Comment by sapegin** [comment]
The second one should be because of https://github.com/buzinas/tslint-eslint-rules/issues/204

**Comment by progre** [comment]
If you using tslint 5.x, this rules will not work.
Some dependended package is not support yet tslint 5.x.

https://github.com/Microsoft/tslint-microsoft-contrib/issues/354

**Comment by sapegin** [comment]
Yup, I’ve made a PR to track that: https://github.com/progre/tslint-config-airbnb/pull/5
