### ISSUE TITLE
Any chance to release a new version to npm?

### ISSUE THREAD

**Issue by rsp** [progre/tslint-config-airbnb#46]
I just spent some time figuring out why my linter config doesn't detect unused variables even though the rule [is there](https://github.com/progre/tslint-config-airbnb/blob/master/tslint.js#L46), I extend tslint-config-airbnb properly and other rules seem to work.

I just realized that there was no release to npm since the unused variable rules was added.

Is there a chance you could make a quick version bump and npm publish? Thanks!

**Note:** According to [the docs](https://palantir.github.io/tslint/rules/no-unused-variable/) the `"check-parameters"` is **experimental**:

> NOTE: this option is experimental and does not work with classes that use abstract method declarations, among other things.

but it seems to be enabled by default. So maybe it's not such a good idea to publish this at this point to npm, after all.

**Comment by bschlenk** [comment]
Also hoping for a release soon so `esSpecCompliant` is included in the `trailing-comma` rule from commit https://github.com/progre/tslint-config-airbnb/commit/9940ffaba278f81985a25ec556aa907126350b1d.

**Comment by progre** [comment]
Today I released the 5.10.0 version.
