### ISSUE TITLE
typescript 3

### ISSUE THREAD

**Issue by mhf-ir** [progre/tslint-config-airbnb#53]
```
warning "tslint-config-airbnb > tslint-microsoft-contrib@5.0.3" has incorrect peer dependency "typescript@^2.1.0".
warning "tslint-config-airbnb > tslint-eslint-rules@5.3.1" has incorrect peer dependency "typescript@^2.2.0".
```
tsc version:
```
./node_modules/.bin/tsc -v
Version 3.0.1
```

**Comment by zerkms** [comment]
Indeed, can you please bump the `tslint-microsoft-contrib` dependency to include at least `v5.2.0`: https://github.com/Microsoft/tslint-microsoft-contrib/milestone/24?closed=1

**Comment by progre** [comment]
done https://github.com/progre/tslint-config-airbnb/commit/0cd45bfc18d466d1d68e4f55632bd50e8f721eb3
