### ISSUE TITLE
tsutils peer dependency unnecessary?

### ISSUE THREAD

**Issue by Kitanotori** [progre/tslint-config-airbnb#8]
Is there some reason for `"tsutils": "1.6.0"` peer dependency? This library does not seem to use it, `tslint-eslint-rules` has had it as ordinary `"^1.4.0"` dependency [since 4.0.0](https://github.com/buzinas/tslint-eslint-rules/blob/v4.0.0/package.json), `tslint-microsoft-contrib` switched its "tsutils": "1.6.0" peer dep to ">=1.6.0" [a month ago](https://github.com/Microsoft/tslint-microsoft-contrib/commit/648f1fb166d393c10bd786291d9b8e4c06f7baba) (not yet [updated to npm](https://github.com/Microsoft/tslint-microsoft-contrib/blob/5.0.0/package.json), though).

**Comment by progre** [comment]
It is adjusted to `tslint-microsoft-contrib`.
Constraints will be removed when the latest version of it is published.

**Comment by Kitanotori** [comment]
`tslint-microsoft-contrib` already enforces the dependency, so I don't see a reason for the redundancy. Anyway, not a big deal but just started digging up the dependencies after shown warnings by yarn.

**Comment by progre** [comment]
Doesn't `peerDependencies` of dependented module need to add to our module?
If so, this is a mistake. Our module's `peerDependencies` needs to remove.

**Comment by dashmug** [comment]
I do agree that this is unnecessary.

**Comment by progre** [comment]
I removed it.
Thx to your pointing out!
